name: EC2-Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Algo to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Remove existing repo from EC2 and stop the processs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo apt -y update
            sudo npm install -g pm2
            sudo pm2 stop server
            sudo pm2 delete server
            sudo rm -rf Algo-Game
 
      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_USERNAME }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd Algo-Game
            touch .env
            echo "${{ secrets.API_ENV }}" > .env
            sudo npm install
            sudo pm2 start --name="server" sudo -- node server.js